---
version: '3.3'
services:
  bgp-frr-20220826:
    container_name: frr-homelab
    image: frrouting/frr:v8.2.2
    volumes:
      - /usr/local/etc/frr/:/etc/frr/
      - /dev/log:/dev/log
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN            
